export const SAVED = 'SAVED';
export const COMPLETED = 'COMPLETED';
export const PROCESSING = 'PROCESSING';
export const FAILED = 'FAILED';
export const SCHEDULED = 'SCHEDULED';
export const SCHEDULE_COMPLETED = 'SCHEDULE_COMPLETED';
export const REQUESTED = 'REQUESTED';

export const RAN_REPORT_STATUSES = [REQUESTED, COMPLETED, SAVED, FAILED, PROCESSING];
export const PROCESSING_REPORT_STATUSES = [REQUESTED, PROCESSING];
export const SCHEDULED_REPORT_STATUSES = [SCHEDULED, SCHEDULE_COMPLETED];
