on:
  workflow_dispatch:
  push:
    branches: [ main ]

name: "Update Transifex on Push"

jobs:
  push-translations-to-transifex:
    name: push-translations-to-transifex
    runs-on: ubuntu-latest
    permissions:
      actions: read
    if: github.repository_owner == 'openmrs'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Push source file using transifex client
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TRANSIFEX_TOKEN }}
